import type { Preview } from '@storybook/react'

import { ThemeProvider, CssBaseline } from '@mui/material';
import { withThemeFromJSXProvider } from '@storybook/addon-themes';

import { lightTheme } from '../src';

import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';

// it seems that are a bug with the code generated by the docs with mui
// it shows React.ForwardRef instead of the mui component name [bug]: https://github.com/storybookjs/storybook/issues/22287
// the code below is a workaround on this, setting the displayName to the components seems to solve the problem
import * as muiComps from '@mui/material'
Object.entries(muiComps).forEach(([key, entry])=> {
  if ('displayName' in entry && entry.displayName === undefined) {
    entry.displayName = key
  }
})

const preview: Preview = {
  tags: ['autodocs'],
  parameters: {
    controls: {
      expanded: true,
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },
    options: {
      storySort: {
        method: 'alphabetical',
        order: [
          'Overview',
          'Design',
          'Icons',
          [
            'Overview',
            'Storyblok',
            'TwoTone',
            'Pictograms',
            '*',
            'Other',
          ],
          'Components',
          'Layout',
          'Pages',
          '*',
          'Mui Components',
          [
            'Overview',
            '*',
          ],
        ],
      },
    }
  },

  decorators: [withThemeFromJSXProvider({
    GlobalStyles: CssBaseline,
    Provider: ThemeProvider,
    themes: {
      light: lightTheme,
    },
    defaultTheme: 'light',
  })]
}

export default preview
