name: Node.js Package

on:
  push:

jobs:
  build-storybook:
    runs-on: ubuntu-latest
    name: Build Storybook
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'yarn'
      - run: yarn install
      - run: yarn build:storybook
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'yarn'
      - name: Install
        run: yarn install
      - name: Check types
        run: yarn check:types
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
